### ISSUE TITLE
'logged_in=true' instead of real content

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-cookies#1]
@ronanyeah How about moving the "[useful cookie](https://github.com/foundersandcoders/ws-session-management#a-useful-cookie)" section from the JWT workshop into this repo?

I'm not sure that it's necessary to separate out "how" to set a cookie from "why" (i.e. what you would want to put in that cookie).

It also might be clearer to have all of the cookie-related content in one workshop and all the JWT-related content in another.

**Comment by ronanyeah** [comment]
@jsms90 

> It will do for now as we are focusing purely on how to transmit cookies

You can probably appreciate that WS3 gets quite complicated quickly also. I want to ensue they understand cookies first. As far as the cookie spec is concerned `logged_in=true` is exactly the same as `auth=oivjrvirmmeori.nh9h49yr4y7`.

**Comment by ronanyeah** [comment]
Yes?

**Comment by ronanyeah** [comment]
For reference, as a guideline the boundaries of this workshop can mostly be inferred from [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies).
