### ISSUE TITLE
use expires instead of maxAge?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-cookies#10]
http://mrcoles.com/blog/cookies-max-age-vs-expires/

> The expires parameter was part of the original cookies baked up by Netscape. In HTTP version 1.1, expires was deprecated and replaced with the easier-to-use max-age—instead of having to specify a date, you can just say how long the cookie can live.

> Unfortunately, none of the current versions of Internet Explorer support max-age, so if you want proper cookie persistence cross-browser, then stick to expires.

**Comment by eliasmalik** [comment]
This is for IE6, 7 and 8. They are all obsolete browsers. Similar to what I said in the flexbox issue, I think legacy support of this nature is different from a generalised focus on accessibility and is closer to being a niche skill that shouldn't necessarily be on the core curriculum.
