### ISSUE TITLE
Workshop composability

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-cookies#22]
Same as [workshop 1](https://github.com/foundersandcoders/ws-password-management/issues/13) - for composability of resources in the `master-reference`

**Comment by ronanyeah** [comment]
So this is cool, but we're not ready for it yet. To be really composable every workshop should have some idea of 'pre-reqs'. I'd like to start looking into this though.

@bradreeder Did the whole pattern language thing have something like this?
