### ISSUE TITLE
Improvements to styling and legibility

### ISSUE THREAD

**Issue by maxgerber** [foundersandcoders/ws-cookies#29]
The information on the page should be more **legible** and more **engaging** through styling, so that it appeals to more visual learners, and becomes **easier to understand** for people for whom english is not a first language.
- [x] We could add bold in places in the workshop so that the text is easier to skim-read
- [ ] We could implement a little more CSS into this example to make it more visually appealing
- [x] Cookie Monster implementation
- [x] More emojis (where applicable) :cookie:
- [x] Change code blocks to have [syntactical highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)

**Comment by astroash** [comment]
![One Cookie](https://i.giphy.com/media/lCjNgUIuXfPA4/200w_d.gif) - Ahahaha.

![Two Cookie](https://media.giphy.com/media/nqEztrBh06uti/giphy.gif) - Authorisation denied
![Three Cookie](https://media.giphy.com/media/EKUvB9uFnm2Xe/giphy.gif) - Destroying a cookie

![making](https://media.giphy.com/media/UXcT54C7P6Hfi/giphy.gif) - Making a cookie
