### ISSUE TITLE
having all 3 buttons on the same page - clearer instructions for what to do

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-cookies#3]
In [this example](https://fac-nodejs-server.glitch.me/) you have pop-up windows appearing when you click on each button. If the intention is for students to create something similar, we could put that in the instructions of the exercise?

But it might just be clearer to have a similar file structure to the one that you would implement in a project? e.g.
```
|- public
|- |- login.html         contains login button
|- |- index.html         homepage that contains logout button
|- src
|- |- router.js
|- |- server.js
```

**Comment by eliasmalik** [comment]
IMO, this may be a bit like the database question in the password management workshop; it dilutes the focus of the workshop slightly.

As is, all they have to worry about is writing a handler to set the cookie, writing a handler to delete the cookie and writing a handler to read the cookie, in each case serving the same HTML back. Routing from `login` back to `index` is something they can concern themselves with during the project.

**Comment by jsms90** [comment]
Yeah I think you're right. Spoke to @alexis-l8 & @bo-bok and they don't think it's at all confusing.

Also, then where would you put the "auth check" button, cos it's not a thing in a real world scenario. This is just about them understanding conceptually how to set a cookie.

Happy to close

**Comment by jsms90** [comment]
Even though it is written in the instructions, some students missed that they were supposed to be redirecting to the same page.

Maybe just make the instructions slightly clearer?

**Comment by ronanyeah** [comment]
> Maybe just make the instructions slightly clearer?

PR welcome.
