### ISSUE TITLE
Screenshots and Infographics

### ISSUE THREAD

**Issue by maxgerber** [foundersandcoders/ws-cookies#31]
More visualisations!

- [x] Screenshots of the Cookies we have written in DevTools
- [ ] A potential infographic [this?](https://www.google.co.uk/imgres?imgurl=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2Foriginals%2Fe6%2F32%2F21%2Fe632215c82dbe6830314d5b96f42200a.jpg&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F252483122832884935%2F&docid=B7nIT_uQ_dHItM&tbnid=opTkzSs6cQsdaM%3A&vet=10ahUKEwj5zZSFsuPWAhUCvBoKHZDRCZkQMwgpKAIwAg..i&w=850&h=3623&itg=1&bih=695&biw=1349&q=web%20cookie%20infographic&ved=0ahUKEwj5zZSFsuPWAhUCvBoKHZDRCZkQMwgpKAIwAg&iact=mrc&uact=8)

**Comment by ronanyeah** [comment]
@maxgerber I think https://github.com/foundersandcoders/ws-cookies/pull/36 ticks off the first one.

More vibrancy is always good but I don't think we should be including external resources as large as that in the workshop. Is there any info in it we should include in the workshop directly?

**Comment by astroash** [comment]
@maxgerber are you happy for this issue to be closed?

**Comment by maxgerber** [comment]
Indeed!
