### ISSUE TITLE
second argument of writeHead should be an array

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-cookies#4]
> res.writeHead(200, { 'Set-Cookie', 'logged_in=true' });

This should be an array instead of an object

i.e.
```
res.writeHead(200, ['Set-Cookie', 'logged_in=true' ], {
  'Content-Type', 'text/html',
  // etc
});
```

**Comment by eliasmalik** [comment]
Where is this signature [documented](https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers)?

I tried this and it doesn't work. Ronan's way works fine.

**Comment by jsms90** [comment]
:thinking: ...no idea

Must have been getting confused with [this](https://nodejs.org/api/http.html#http_response_setheader_name_value)
> response.setHeader('Set-Cookie', ['type=ninja', 'language=javascript']);

Total nonsense :flushed:
