### ISSUE TITLE
add instructions on how to set multiple cookies with node

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/ws-cookies#44]
I think it could be useful to mention this.

**Comment by oliverjam** [comment]
Yeah this just came up with FAC19 and I had no idea how to set multiple headers in Node.

For future reference you can pass arrays as header values to both `setHeader` and `writeHead`:

```js
response.writeHead(302, {
  location: "/",
  "set-cookie": [
    "loggedIn=true; Max-Age: 2000;",
    "otherThing=true; Max-Age: 3000;",
  ],
})
```
