### ISSUE TITLE
use of glitch makes it difficult to collaborate via issues & PRs

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-cookies#5]
Relates https://github.com/foundersandcoders/master-reference/issues/242

This is a difficult one, because I kind of love the idea of using glitch. It reminds me a lot of [inventing on principle](https://vimeo.com/36579366)!

The biggest downside I see here though is that it makes collaboration on this workshop harder. We can raise issues within this repo about the content of the files in glitch (e.g. #2 on the `parse` issue), but you can't link to the specific lines. More importantly, no one can raise PRs to change it.

The content of the FAC curriculum is shared and updated by multiple different people. If we want to enable collaboration, we would need to give everyone in FAC access rights to changing the content of this glitch project. But without a version control system behind it, we can't track the changes that are made in any way. Without a PR workflow, no one can review potential changes that someone suggests.

**Comment by ronanyeah** [comment]
You can export a glitch project very easily, then push it to github.

**Comment by ronanyeah** [comment]
Ah you mean for curriculum creators. It's too late to make changes like that unfortunately but we can address it it future.

**Comment by jsms90** [comment]
There's also the issue of the internet going down and then not being able to access the project. A very real concern in Gaza, but also a concern in London :worried: 

From our hangouts conversation, it seems everyone is fine for this to go ahead. I'd love us to figure out a way of using glitch effectively in future.

Let's close this issue if/when the files are now in this repo.
