### ISSUE TITLE
add links to articles that explain what an XSS and MITM attacks are?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-cookies#8]
The [cookie flags table](https://github.com/foundersandcoders/ws-cookies#cookie-flags) contains explanations for `HttpOnly` and `Secure`. But students probably don't know what these attacks are, so they won't know how important it is for these flags to be set.

**Comment by ronanyeah** [comment]
I think this has been handled by @alexis-l8 https://github.com/foundersandcoders/ws-cookies/commit/16f26a8c76303df414941f1672223ba6ca115f46
